In [70]:
import xarray as xr
import pandas as pd
import numpy as np

from sklearn.model_selection import train_test_split
from sklearn import svm, metrics

In [35]:
tors_pcs = pd.read_csv('tors_10pcs_2.csv')
tors_pcs['tor'] = tors_pcs['tor'].astype(int)

In [36]:
tors_pcs.head(10)

date  mode        pcs  tor
0  1985-05-17     0  636.52020    0
1  1985-05-17     1   27.60290    0
2  1985-05-17     2 -215.67738    0
3  1985-05-17     3 -231.10164    0
4  1985-05-17     4 -188.53261    0
5  1985-05-17     5 -497.95070    0
6  1985-05-17     6  276.91360    0
7  1985-05-17     7 -154.75032    0
8  1985-05-17     8   81.08732    0
9  1985-05-17     9 -216.62033    0

In [75]:
def svm_classify(nmodes, kernel):
    features = tors_pcs[tors_pcs['mode'] < nmodes]['pcs'].values.reshape(-1, nmodes)
    targets = tors_pcs[tors_pcs['mode'] == 0].tor.values
    assert features.shape[0] == targets.shape[0]
    
    X_train, X_test, y_train, y_test = train_test_split(features, targets)
    print('Training data and target sizes: \n{}, {}'.format(X_train.shape,y_train.shape))
    print('Test data and target sizes: \n{}, {}'.format(X_test.shape,y_test.shape))
    
    classifier = svm.SVC(kernel=kernel)
    classifier.fit(X_train, y_train)
    
    y_pred = classifier.predict(X_test)
    return classifier, y_test, y_pred

In [109]:
classifier, y_test, y_pred = svm_classify(nmodes=4, kernel='sigmoid')

Training data and target sizes: 
(382, 4), (382,)
Test data and target sizes: 
(128, 4), (128,)


/Users/jitang/anaconda/envs/storm_analysis_env/lib/python3.7/site-packages/sklearn/svm/base.py:196: FutureWarning: The default value of gamma will change from 'auto' to 'scale' in version 0.22 to account better for unscaled features. Set gamma explicitly to 'auto' or 'scale' to avoid this warning.
  "avoid this warning.", FutureWarning)


In [110]:
print(metrics.classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.51      0.59      0.55        66
           1       0.48      0.40      0.44        62

   micro avg       0.50      0.50      0.50       128
   macro avg       0.50      0.50      0.49       128
weighted avg       0.50      0.50      0.50       128



In [111]:
y_pred, y_test

(array([1, 1, 1, 0, 0, 0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0,
        0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 1,
        0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1,
        1, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0,
        0, 0, 0, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 1, 0,
        0, 0, 0, 1, 0, 1, 1, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0]),
 array([1, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 1,
        1, 1, 1, 0, 0, 0, 0, 1, 1, 0, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0,
        0, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1,
        0, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
        0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1,
        1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 1, 0, 1, 0, 0, 1]))

In [112]:
print("Confusion matrix:\n%s" % metrics.confusion_matrix(y_test, y_pred))

Confusion matrix:
[[39 27]
 [37 25]]
